---
apiVersion: v1
kind: Service
metadata:
  name: "oppv-widget"
  namespace: "default"
  labels:
    app: "oppv-widget"
    version: "0.0.1"
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: "oppv-widget"
    version: "0.0.1"
    
