---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "${APP_NAME}"
  namespace: "${APP_NS}"
  labels:
    app: "${APP_NAME}"
    version: "${VERSION:-0.0.1}"    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "${APP_NAME}"
      version: "${VERSION:-0.0.1}"
  template:
    metadata:
      labels:
        app: "${APP_NAME}"
        version: "${VERSION:-0.0.1}"
    spec:
      serviceAccount: "${SERVICE_ACCOUNT:-default}"
      containers:
      - env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              key: config-env
              name: "${APP_NAME}"
        image: "${IMAGE_NAME}"
        imagePullPolicy: Always
        name: "${APP_NAME}"
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
