---
apiVersion: v1
kind: Service
metadata:
  name: "${APP_NAME}"
  namespace: "${APP_NS}"
  labels:
    app: "${APP_NAME}"
    version: "${VERSION:-0.0.1}"
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: "${APP_NAME}"
    version: "${VERSION:-0.0.1}"
    
